/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.BookMax_con;

import db.DBConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;

import Model.Books;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Random;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Max point galgamuwa
 */
public class BookPortal extends javax.swing.JFrame {
    
    DefaultTableModel dtm;

    /**
     * Creates new form MemberPortal
     */
    public BookPortal() throws ClassNotFoundException, SQLException {
        initComponents();
        dtm = (DefaultTableModel) Book_Tbl.getModel();
        LoadAllBooks();
        Press.setEnabled(false);
        loadOrdeID();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ddd = new javax.swing.JPanel();
        LogoImage = new javax.swing.JLabel();
        NavigationBarPanel = new javax.swing.JPanel();
        LibrararyName = new javax.swing.JLabel();
        TimeAndDate = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Combo_Rack = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        Combo_colomn = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        Book_Tbl = new javax.swing.JTable();
        JTFBookID = new javax.swing.JTextField();
        JTFBookName = new javax.swing.JTextField();
        JTFAuthor = new javax.swing.JTextField();
        JTFISBN = new javax.swing.JTextField();
        JTFPublisher = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        ComoboYN = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        Combo_Row = new javax.swing.JComboBox<>();
        Update_btn = new javax.swing.JButton();
        Submit_btn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        Press = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        ddd.setBackground(new java.awt.Color(255, 255, 255));
        ddd.setForeground(new java.awt.Color(0, 153, 102));

        LogoImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hj.png"))); // NOI18N

        NavigationBarPanel.setBackground(new java.awt.Color(0, 102, 102));

        LibrararyName.setBackground(new java.awt.Color(0, 102, 102));
        LibrararyName.setFont(new java.awt.Font("Snap ITC", 1, 34)); // NOI18N
        LibrararyName.setForeground(new java.awt.Color(255, 255, 255));
        LibrararyName.setText("Page One Library Management System");

        javax.swing.GroupLayout NavigationBarPanelLayout = new javax.swing.GroupLayout(NavigationBarPanel);
        NavigationBarPanel.setLayout(NavigationBarPanelLayout);
        NavigationBarPanelLayout.setHorizontalGroup(
            NavigationBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavigationBarPanelLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(LibrararyName, javax.swing.GroupLayout.PREFERRED_SIZE, 828, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TimeAndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        NavigationBarPanelLayout.setVerticalGroup(
            NavigationBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavigationBarPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(LibrararyName, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(TimeAndDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 187, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        jLabel1.setBackground(new java.awt.Color(0, 153, 153));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 102));
        jLabel1.setText("Book ID");

        jLabel3.setBackground(new java.awt.Color(0, 153, 153));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 102));
        jLabel3.setText("Book Name");

        jLabel4.setBackground(new java.awt.Color(0, 153, 153));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 102));
        jLabel4.setText("Author");

        jLabel5.setBackground(new java.awt.Color(0, 153, 153));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 102));
        jLabel5.setText("ISBN No");

        jLabel6.setBackground(new java.awt.Color(0, 153, 153));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 102));
        jLabel6.setText("Publisher");

        jLabel7.setBackground(new java.awt.Color(0, 153, 153));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 102));
        jLabel7.setText("Rack Number");

        Combo_Rack.setBackground(new java.awt.Color(0, 102, 102));
        Combo_Rack.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Combo_Rack.setForeground(new java.awt.Color(255, 255, 255));
        Combo_Rack.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        jLabel8.setBackground(new java.awt.Color(0, 153, 153));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 102));
        jLabel8.setText("Colomn No");

        Combo_colomn.setBackground(new java.awt.Color(0, 102, 102));
        Combo_colomn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Combo_colomn.setForeground(new java.awt.Color(255, 255, 255));
        Combo_colomn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        Combo_colomn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Combo_colomnActionPerformed(evt);
            }
        });

        Book_Tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Book ID", "Book Name", "Author", "ISBN No", "Publisher", "Rack No", "Colomn No", "Row No", "Donation"
            }
        ));
        Book_Tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Book_TblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Book_TblMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(Book_Tbl);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 102));
        jLabel9.setText("Is this Donation?");

        ComoboYN.setBackground(new java.awt.Color(0, 102, 102));
        ComoboYN.setForeground(new java.awt.Color(255, 255, 255));
        ComoboYN.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No", "Yes" }));
        ComoboYN.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComoboYNItemStateChanged(evt);
            }
        });
        ComoboYN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComoboYNActionPerformed(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(0, 153, 153));
        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 153, 102));
        jLabel13.setText("Row No");

        Combo_Row.setBackground(new java.awt.Color(0, 102, 102));
        Combo_Row.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Combo_Row.setForeground(new java.awt.Color(255, 255, 255));
        Combo_Row.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        Combo_Row.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Combo_RowActionPerformed(evt);
            }
        });

        Update_btn.setBackground(new java.awt.Color(0, 153, 102));
        Update_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Update_btn.setForeground(new java.awt.Color(255, 255, 255));
        Update_btn.setText("Update");
        Update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_btnActionPerformed(evt);
            }
        });

        Submit_btn.setBackground(new java.awt.Color(0, 153, 102));
        Submit_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Submit_btn.setForeground(new java.awt.Color(255, 255, 255));
        Submit_btn.setText("Submit");
        Submit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submit_btnActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 153, 102));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 153, 102));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Refresh");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(0, 153, 102));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Home");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(0, 153, 102));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Check Position");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        Press.setBackground(new java.awt.Color(0, 153, 102));
        Press.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Press.setForeground(new java.awt.Color(255, 255, 255));
        Press.setText("Donation Panel");
        Press.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PressActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dddLayout = new javax.swing.GroupLayout(ddd);
        ddd.setLayout(dddLayout);
        dddLayout.setHorizontalGroup(
            dddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dddLayout.createSequentialGroup()
                .addComponent(LogoImage)
                .addGap(0, 0, 0)
                .addComponent(NavigationBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(dddLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(dddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dddLayout.createSequentialGroup()
                        .addGroup(dddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dddLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Combo_Rack, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Combo_colomn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Combo_Row, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton6))
                            .addGroup(dddLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(35, 35, 35)
                                .addComponent(JTFBookName, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(dddLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(76, 76, 76)
                                .addComponent(JTFAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 479, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(dddLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(65, 65, 65)
                        .addComponent(JTFBookID, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(236, 236, 236)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(ComoboYN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Press)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(dddLayout.createSequentialGroup()
                        .addGroup(dddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(53, 53, 53)
                        .addGroup(dddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JTFPublisher, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                            .addComponent(JTFISBN))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(dddLayout.createSequentialGroup()
                .addGroup(dddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, dddLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1214, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dddLayout.createSequentialGroup()
                        .addGap(415, 415, 415)
                        .addComponent(Submit_btn)
                        .addGap(18, 18, 18)
                        .addComponent(Update_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        dddLayout.setVerticalGroup(
            dddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dddLayout.createSequentialGroup()
                .addGroup(dddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LogoImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NavigationBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dddLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(dddLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(dddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(JTFBookID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(ComoboYN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Press))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(dddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(JTFBookName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 13, Short.MAX_VALUE)
                        .addGroup(dddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(JTFAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(dddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(JTFISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(dddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JTFPublisher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(20, 20, 20)
                        .addGroup(dddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Combo_Rack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(Combo_colomn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(Combo_Row, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6)
                            .addComponent(jLabel7))
                        .addGap(25, 25, 25)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(dddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Update_btn)
                    .addComponent(Submit_btn)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addGap(65, 65, 65))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ddd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ddd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Submit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Submit_btnActionPerformed
        
        try {
            
            String racks = Combo_Rack.getSelectedItem().toString();
            String colomns = Combo_colomn.getSelectedItem().toString();
            String Row = Combo_Row.getSelectedItem().toString();
            
            Books search = BookMax_con.searchBook(racks, colomns, Row);
            if (search == null) {
                
                try {
                    String bookID = JTFBookID.getText();
                    String bookName = JTFBookName.getText();
                    String Author = JTFAuthor.getText();
                    String ISBNO = JTFISBN.getText();
                    String pub = JTFPublisher.getText();
                    String rack = Combo_Rack.getSelectedItem().toString();
                    String colomn = Combo_colomn.getSelectedItem().toString();
                    String row = Combo_Row.getSelectedItem().toString();
                    String donation = ComoboYN.getSelectedItem().toString();
                    
                    Books book = new Books();
                    book.setBOOK_ID(bookID);
                    book.setBook_Name(bookName);
                    book.setAuthor(Author);
                    book.setISBN_No(ISBNO);
                    book.setPublisher(pub);
                    
                    book.setRack(rack);
                    book.setColomn(colomn);
                    book.setRow(row);
                    book.setDonation(donation);
                    
                    boolean add = BookMax_con.addBook(book);
                    if (add) {
                        JOptionPane.showMessageDialog(this, "Done");
                    } else {
                        JOptionPane.showMessageDialog(this, "Something went Wrong");
                    }

//                if (addmember) {
//                    JOptionPane.showMessageDialog(this, "Done");
//                } else {
//                    JOptionPane.showMessageDialog(this, "Something went wrong");
//                }
                    LoadAllBooks();
                    clearAll();
                    
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(BookPortal.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(BookPortal.class.getName()).log(Level.SEVERE, null, ex);
                } catch (Exception ex) {
                    Logger.getLogger(BookPortal.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            } else {
                JOptionPane.showMessageDialog(this, "Please check entered details", "Warning", JOptionPane.ERROR_MESSAGE);
            }

//            try {
//                String bookID = JTFBookID.getText();
//                String bookName = JTFBookName.getText();
//                String Author = JTFAuthor.getText();
//                String ISBNO = JTFISBN.getText();
//                String pub = JTFPublisher.getText();
//                String rack = Combo_Rack.getSelectedItem().toString();
//                String colomn = Combo_colomn.getSelectedItem().toString();
//                String row = Combo_Row.getSelectedItem().toString();
//                String donation = ComoboYN.getSelectedItem().toString();
//                String Donator = DonatorName.getText();
//                String demail = DEmail.getText();
//                String dMobile = DMobileNo.getText();
//                
//                BookDTO book = new BookDTO(bookID, bookName, Author, ISBNO, pub, rack, colomn, row, donation, Donator, demail, dMobile);
//                boolean addmember = Member_controller.submit(book);
//                if (addmember) {
//                    JOptionPane.showMessageDialog(this, "Done");
//                } else {
//                    JOptionPane.showMessageDialog(this, "Something went wrong");
//                }
//                
//            } catch (ClassNotFoundException ex) {
//                Logger.getLogger(BookPortal.class.getName()).log(Level.SEVERE, null, ex);
//            } catch (SQLException ex) {
//                Logger.getLogger(BookPortal.class.getName()).log(Level.SEVERE, null, ex);
//            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BookPortal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(BookPortal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Submit_btnActionPerformed

    private void ComoboYNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComoboYNActionPerformed
        String YOrNo = ComoboYN.getSelectedItem().toString();
        if (YOrNo == "Yes") {
//          Login ss = new Login();
//          ss.setVisible(true);
            Press.setEnabled(true);
            
        } else {
            Press.setEnabled(false);
        }

    }//GEN-LAST:event_ComoboYNActionPerformed

    private void Combo_colomnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Combo_colomnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Combo_colomnActionPerformed

    private void Combo_RowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Combo_RowActionPerformed
//        try {
//            String rack = Combo_Rack.getSelectedItem().toString();
//            String colomn = Combo_colomn.getSelectedItem().toString();
//            String Row = Combo_Row.getSelectedItem().toString();
//
//            BookDTO search = Issue_controller.searchBook(rack, colomn, Row);
//            if (search == null) {
//                
//            } else {
//                JOptionPane.showMessageDialog(this, "This book already issued");
//                bookid();
//            }
//            
//              
//            
//
//        } catch (ClassNotFoundException ex) {
//            Logger.getLogger(BookPortal.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (SQLException ex) {
//            Logger.getLogger(BookPortal.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_Combo_RowActionPerformed

    private void Book_TblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Book_TblMouseClicked
        int selectedRow = Book_Tbl.getSelectedRow();
        
        String bookid = dtm.getValueAt(selectedRow, 0).toString();
        String bookName = dtm.getValueAt(selectedRow, 1).toString();
        String Author = dtm.getValueAt(selectedRow, 2).toString();
        String ISBN = dtm.getValueAt(selectedRow, 3).toString();
        String Publisher = dtm.getValueAt(selectedRow, 4).toString();
        String Rack = dtm.getValueAt(selectedRow, 5).toString();
        String colomn = dtm.getValueAt(selectedRow, 6).toString();
        String row = dtm.getValueAt(selectedRow, 7).toString();
        String donation = dtm.getValueAt(selectedRow, 8).toString();
//        String dname = dtm.getValueAt(selectedRow, 9).toString();
//        String demail = dtm.getValueAt(selectedRow, 10).toString();
//        String mobile = dtm.getValueAt(selectedRow, 11).toString();

        JTFBookID.setText(bookid);
        JTFBookName.setText(bookName);
        JTFAuthor.setText(Author);
        JTFISBN.setText(ISBN);
        JTFPublisher.setText(Publisher);
        Combo_Rack.setSelectedItem(Rack);
        Combo_colomn.setSelectedItem(colomn);
        Combo_Row.setSelectedItem(row);
        ComoboYN.setSelectedItem(donation);
//
//        int selectedRow = Member_tbl.getSelectedRow();
//
//        String member_ID = dtm.getValueAt(selectedRow, 0).toString();
//        String memberName = dtm.getValueAt(selectedRow, 1).toString();
//
//        String birthdate = dtm.getValueAt(selectedRow, 2).toString();
//        String email = dtm.getValueAt(selectedRow, 3).toString();
//        String telephone = dtm.getValueAt(selectedRow, 4).toString();
//
//        MemberID.setText(member_ID);
//        MemberName.setText(memberName);
//
//        ((JTextField) Birthdate.getDateEditor().getUiComponent()).setText(birthdate);
//        Emailadrress.setText(email);
//        PhoneNumber.setText(telephone);
//        DonatorName.setText(dname);
//        DEmail.setText(demail);
//        DMobileNo.setText(mobile);

    }//GEN-LAST:event_Book_TblMouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {
            String rack = Combo_Rack.getSelectedItem().toString();
            String colomn = Combo_colomn.getSelectedItem().toString();
            String Row = Combo_Row.getSelectedItem().toString();
            
            Books search = BookMax_con.searchBook(rack, colomn, Row);
            if (search == null) {
                //  Submit_btn.setEnabled(true);

                JOptionPane.showMessageDialog(this, "Book is successfully Placed");
                
            } else {
                JOptionPane.showMessageDialog(this, "This position is reserved.Please Select Another position", "Warning", JOptionPane.ERROR_MESSAGE);
                bookid();
                
            }
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BookPortal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(BookPortal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void Book_TblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Book_TblMouseEntered
        

    }//GEN-LAST:event_Book_TblMouseEntered

    private void PressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PressActionPerformed

    }//GEN-LAST:event_PressActionPerformed

    private void ComoboYNItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComoboYNItemStateChanged

    }//GEN-LAST:event_ComoboYNItemStateChanged

    private void Update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_btnActionPerformed
        try {
            String racks = Combo_Rack.getSelectedItem().toString();
            String colomns = Combo_colomn.getSelectedItem().toString();
            String Row = Combo_Row.getSelectedItem().toString();
            
            Books search = BookMax_con.searchBook(racks, colomns, Row);
            if (search == null || search == search) {
                try {
                    
                    String bi = JTFBookID.getText();
                    String bn = JTFBookName.getText();
                    String au = JTFAuthor.getText();
                    String Is = JTFISBN.getText();
                    String Pub = JTFPublisher.getText();
                    String rk = Combo_Rack.getSelectedItem().toString();
                    String Co = Combo_colomn.getSelectedItem().toString();
                    String ro = Combo_Row.getSelectedItem().toString();
                    String dona = ComoboYN.getSelectedItem().toString();
                    
                    Books b = new Books();
                    b.setBOOK_ID(bi);
                    b.setBook_Name(bn);
                    b.setAuthor(au);
                    b.setISBN_No(Is);
                    b.setPublisher(Pub);
                    b.setRack(rk);
                    b.setColomn(Co);
                    b.setRow(ro);
                    b.setDonation(dona);

//            String racks = Combo_Rack.getSelectedItem().toString();
//            String colomns = Combo_colomn.getSelectedItem().toString();
//            String Row = Combo_Row.getSelectedItem().toString();
                    boolean update = BookMax_con.update(b);
                    if (update) {
                        JOptionPane.showMessageDialog(this, "Done");
                    } else {
                        JOptionPane.showMessageDialog(this, "No");
                    }
                    LoadAllBooks();
                    
                    clearAll();
                } catch (Exception ex) {
                    Logger.getLogger(BookPortal.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Cannot update");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BookPortal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(BookPortal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Update_btnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            String Book_id = JTFBookID.getText();
            boolean deletecustomer = BookMax_con.deleteBook(Book_id);
//            if (deletecustomer) {
//                JOptionPane.showConfirmDialog(null, "Are You Sure?", "Delete", JOptionPane.YES_NO_OPTION);
//            } else {
//                JOptionPane.showMessageDialog(this, "NO");
//            }
            int opt = JOptionPane.showConfirmDialog(null, "Are You Sure?", "Delete", JOptionPane.YES_NO_OPTION);
            if (opt == 0 && deletecustomer) {
                JOptionPane.showMessageDialog(this, "Deleted Successfully");
            }
            clearAll();
            LoadAllBooks();
            
        } catch (Exception ex) {
            Logger.getLogger(BookPortal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        clearAll();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        setVisible(false);
        DashBoard db = new DashBoard();
        db.setVisible(true);
        

    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new BookPortal().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(BookPortal.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(BookPortal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Book_Tbl;
    private javax.swing.JComboBox<String> Combo_Rack;
    private javax.swing.JComboBox<String> Combo_Row;
    private javax.swing.JComboBox<String> Combo_colomn;
    private javax.swing.JComboBox<String> ComoboYN;
    private javax.swing.JTextField JTFAuthor;
    private javax.swing.JTextField JTFBookID;
    private javax.swing.JTextField JTFBookName;
    private javax.swing.JTextField JTFISBN;
    private javax.swing.JTextField JTFPublisher;
    private javax.swing.JLabel LibrararyName;
    private javax.swing.JLabel LogoImage;
    private javax.swing.JPanel NavigationBarPanel;
    private javax.swing.JButton Press;
    private javax.swing.JButton Submit_btn;
    private javax.swing.JLabel TimeAndDate;
    private javax.swing.JButton Update_btn;
    private javax.swing.JPanel ddd;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
public void bookid() {
        
        Combo_Row.setSelectedIndex(0);
        Combo_Rack.setSelectedIndex(0);
        Combo_colomn.setSelectedIndex(0);
        
    }
    
    public void clearAll() {
        JTFBookID.setText("");
        JTFBookName.setText("");
        JTFAuthor.setText("");
        JTFISBN.setText("");
        JTFPublisher.setText("");
        Combo_Rack.setSelectedIndex(0);
        Combo_colomn.setSelectedIndex(0);
        Combo_Row.setSelectedIndex(0);
        ComoboYN.setSelectedIndex(0);
        
    }
    
    private void LoadAllBooks() {
        try {
            ArrayList<Books> allBooks = BookMax_con.getAllBooks();
            dtm.setRowCount(0);
            for (Books c : allBooks) {
                Object[] rowData = {c.getBOOK_ID(), c.getBook_Name(), c.getAuthor(), c.getISBN_No(), c.getPublisher(), c.getRack(), c.getColomn(), c.getRow(), c.getDonation()};
                dtm.addRow(rowData);
            }
        } catch (Exception ex) {
            Logger.getLogger(BookPortal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void loadOrdeID() {
        int i = new Random().nextInt(90000);
       JTFBookID.setText("ID" + i);
    }
}
