/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.MemberM_Controller;
import Model.Member;
import db.DBConnection;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Max point galgamuwa
 */
public class MemberPortal extends javax.swing.JFrame {

    DefaultTableModel dtm;

    /**
     * Creates new form MemberPortal
     */
    public MemberPortal() throws Exception {
        initComponents();

        dtm = (DefaultTableModel) Member_tbl.getModel();
        LoadallMember();
        SlipArea.setEditable(false);
        JTFMembership.setEditable(false);

        Print.setEnabled(false);
        Reset.setEnabled(false);
        JTFMemberID.setEditable(false);
        loadOrdeID();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FullPanel = new javax.swing.JPanel();
        NavigationBarPanel = new javax.swing.JPanel();
        LibrararyName = new javax.swing.JLabel();
        TimeAndDate = new javax.swing.JLabel();
        LogoImage = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        JTFMemberID = new javax.swing.JTextField();
        JTFMemberName = new javax.swing.JTextField();
        JTFEmail = new javax.swing.JTextField();
        JTFTelephone = new javax.swing.JTextField();
        JTFMembership = new javax.swing.JTextField();
        ComboAge = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        Member_tbl = new javax.swing.JTable();
        Birthdate = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        SlipArea = new javax.swing.JTextArea();
        Print = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        SubmitJbtn = new javax.swing.JButton();
        ModifyJbtn = new javax.swing.JButton();
        DeleteJbtn = new javax.swing.JButton();
        RefreshJbtn = new javax.swing.JButton();
        SubmitJbtn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        FullPanel.setBackground(new java.awt.Color(255, 255, 255));

        NavigationBarPanel.setBackground(new java.awt.Color(0, 102, 102));

        LibrararyName.setBackground(new java.awt.Color(0, 102, 102));
        LibrararyName.setFont(new java.awt.Font("Snap ITC", 1, 34)); // NOI18N
        LibrararyName.setForeground(new java.awt.Color(255, 255, 255));
        LibrararyName.setText("Page One Library Management System");

        LogoImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hj.png"))); // NOI18N

        javax.swing.GroupLayout NavigationBarPanelLayout = new javax.swing.GroupLayout(NavigationBarPanel);
        NavigationBarPanel.setLayout(NavigationBarPanelLayout);
        NavigationBarPanelLayout.setHorizontalGroup(
            NavigationBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavigationBarPanelLayout.createSequentialGroup()
                .addComponent(LogoImage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LibrararyName, javax.swing.GroupLayout.PREFERRED_SIZE, 828, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110)
                .addComponent(TimeAndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        NavigationBarPanelLayout.setVerticalGroup(
            NavigationBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TimeAndDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(NavigationBarPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(LibrararyName, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(LogoImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel1.setBackground(new java.awt.Color(0, 153, 153));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 102));
        jLabel1.setText("Member ID");

        jLabel2.setBackground(new java.awt.Color(0, 153, 153));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 102));
        jLabel2.setText("Date Of Birth");

        jLabel3.setBackground(new java.awt.Color(0, 153, 153));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 102));
        jLabel3.setText("Member Name");

        jLabel4.setBackground(new java.awt.Color(0, 153, 153));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 102));
        jLabel4.setText("Age");

        jLabel5.setBackground(new java.awt.Color(0, 153, 153));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 102));
        jLabel5.setText("Email Address");

        jLabel6.setBackground(new java.awt.Color(0, 153, 153));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 102));
        jLabel6.setText("Telephone Number");

        jLabel7.setBackground(new java.awt.Color(0, 153, 153));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 102));
        jLabel7.setText("Membership Payment");

        JTFMemberID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFMemberIDActionPerformed(evt);
            }
        });

        JTFMemberName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFMemberNameActionPerformed(evt);
            }
        });

        JTFEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFEmailActionPerformed(evt);
            }
        });

        JTFTelephone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFTelephoneActionPerformed(evt);
            }
        });

        JTFMembership.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFMembershipActionPerformed(evt);
            }
        });

        ComboAge.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Your Age", "10-12", "12-15", "15-20", "20-25", "30-35", "35+" }));
        ComboAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboAgeActionPerformed(evt);
            }
        });

        Member_tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Member ID", "Member Name", "Birthdate", "Age", "Email", "Telephone", "M. Payment"
            }
        ));
        Member_tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Member_tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Member_tbl);

        SlipArea.setColumns(20);
        SlipArea.setRows(5);
        jScrollPane2.setViewportView(SlipArea);

        Print.setBackground(new java.awt.Color(0, 153, 51));
        Print.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Print.setForeground(new java.awt.Color(255, 255, 255));
        Print.setText("Print");
        Print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintActionPerformed(evt);
            }
        });

        Reset.setBackground(new java.awt.Color(255, 51, 0));
        Reset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Reset.setForeground(new java.awt.Color(255, 255, 255));
        Reset.setText("Reset");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        SubmitJbtn.setBackground(new java.awt.Color(0, 153, 51));
        SubmitJbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SubmitJbtn.setForeground(new java.awt.Color(255, 255, 255));
        SubmitJbtn.setText("Submit");
        SubmitJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitJbtnActionPerformed(evt);
            }
        });

        ModifyJbtn.setBackground(new java.awt.Color(0, 153, 51));
        ModifyJbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ModifyJbtn.setForeground(new java.awt.Color(255, 255, 255));
        ModifyJbtn.setText("Modify");
        ModifyJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyJbtnActionPerformed(evt);
            }
        });

        DeleteJbtn.setBackground(new java.awt.Color(0, 153, 51));
        DeleteJbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DeleteJbtn.setForeground(new java.awt.Color(255, 255, 255));
        DeleteJbtn.setText("Delete");
        DeleteJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteJbtnActionPerformed(evt);
            }
        });

        RefreshJbtn.setBackground(new java.awt.Color(0, 153, 51));
        RefreshJbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RefreshJbtn.setForeground(new java.awt.Color(255, 255, 255));
        RefreshJbtn.setText("Refresh");
        RefreshJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshJbtnActionPerformed(evt);
            }
        });

        SubmitJbtn1.setBackground(new java.awt.Color(0, 153, 51));
        SubmitJbtn1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SubmitJbtn1.setForeground(new java.awt.Color(255, 255, 255));
        SubmitJbtn1.setText("Home");
        SubmitJbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitJbtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FullPanelLayout = new javax.swing.GroupLayout(FullPanel);
        FullPanel.setLayout(FullPanelLayout);
        FullPanelLayout.setHorizontalGroup(
            FullPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NavigationBarPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(FullPanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(FullPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FullPanelLayout.createSequentialGroup()
                        .addGroup(FullPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FullPanelLayout.createSequentialGroup()
                                .addGroup(FullPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(FullPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JTFTelephone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Birthdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ComboAge, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(FullPanelLayout.createSequentialGroup()
                                .addGroup(FullPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(FullPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JTFMemberID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JTFMemberName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(FullPanelLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JTFEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(FullPanelLayout.createSequentialGroup()
                                .addGroup(FullPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(FullPanelLayout.createSequentialGroup()
                                        .addGap(221, 221, 221)
                                        .addComponent(JTFMembership, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel7))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(55, 55, 55)
                        .addGroup(FullPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SubmitJbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ModifyJbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DeleteJbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RefreshJbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(FullPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FullPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Print, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SubmitJbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );
        FullPanelLayout.setVerticalGroup(
            FullPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FullPanelLayout.createSequentialGroup()
                .addComponent(NavigationBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(FullPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FullPanelLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(FullPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(JTFMemberID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addGroup(FullPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(FullPanelLayout.createSequentialGroup()
                                .addGroup(FullPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(FullPanelLayout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addGroup(FullPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel3)
                                            .addComponent(JTFMemberName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(FullPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(FullPanelLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel2))
                                            .addGroup(FullPanelLayout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(Birthdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(FullPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(ComboAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(FullPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(JTFTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(FullPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(JTFEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel7)
                                        .addGap(16, 16, 16)
                                        .addComponent(JTFMembership, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(FullPanelLayout.createSequentialGroup()
                                        .addGap(39, 39, 39)
                                        .addComponent(SubmitJbtn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ModifyJbtn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(DeleteJbtn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(RefreshJbtn)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(24, 24, 24))
                    .addGroup(FullPanelLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(Print)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Reset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SubmitJbtn1)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FullPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FullPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintActionPerformed
        try {
            SlipArea.print();
        } catch (PrinterException ex) {
            Logger.getLogger(MemberPortal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_PrintActionPerformed

    private void ComboAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboAgeActionPerformed
        if (ComboAge.getSelectedItem().toString() == ("10-12")) {
            JTFMembership.setText(" Rs .50");
        }
        if (ComboAge.getSelectedItem().toString() == ("12-15")) {
            JTFMembership.setText(" Rs .75");
        }
        if (ComboAge.getSelectedItem().toString() == ("15-20")) {
            JTFMembership.setText(" Rs .100");
        }
        if (ComboAge.getSelectedItem().toString() == ("20-25")) {
            JTFMembership.setText(" Rs .125");
        }
        if (ComboAge.getSelectedItem().toString() == ("25-35")) {
            JTFMembership.setText(" Rs .150");
        }
        if (ComboAge.getSelectedItem().toString() == ("35+")) {
            JTFMembership.setText(" Rs .200");
        }
    }//GEN-LAST:event_ComboAgeActionPerformed

    private void SubmitJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitJbtnActionPerformed
        try {
            String mi = JTFMemberID.getText();
            String mn = JTFMemberName.getText();
            String bday = ((JTextField) Birthdate.getDateEditor().getUiComponent()).getText();
            String age = ComboAge.getSelectedItem().toString();
            String email = JTFEmail.getText();
            int tele = Integer.parseInt(JTFTelephone.getText());
            String mp = JTFMembership.getText();

            Member member = new Member(mi, mn, bday, age, email, tele, mp);
            boolean submit = MemberM_Controller.addMember(member);

            if (submit) {

                
                SlipArea.setText("**********************************************************\n");
                SlipArea.setText(SlipArea.getText() + "*                          Membership Card                                  *\n");
                SlipArea.setText(SlipArea.getText() + "**********************************************************\n");
                Date obj = new Date();
                String date = obj.toString();
                SlipArea.setText(SlipArea.getText() + "\n" + date + "\n\n");
                SlipArea.setText(SlipArea.getText() + "Member ID                    :" + JTFMemberID.getText() + "\n\n");
                SlipArea.setText(SlipArea.getText() + "Member Name             :" + JTFMemberName.getText() + "\n\n");
                SlipArea.setText(SlipArea.getText() + "Date Of Birth                 :" + ((JTextField) Birthdate.getDateEditor().getUiComponent()).getText() + "\n\n");
                SlipArea.setText(SlipArea.getText() + "Email                             :" + JTFEmail.getText() + "\n\n");
                SlipArea.setText(SlipArea.getText() + "Mobile Number            :" + JTFTelephone.getText() + "\n\n");
                SlipArea.setText(SlipArea.getText() + "Membership Payment :" + JTFMembership.getText() + "\n\n");
                SlipArea.setText(SlipArea.getText() + "***********************************************************\n");
                SlipArea.setText(SlipArea.getText() + "This Card is the Property of PageOne public Library.\n");
                SlipArea.setText(SlipArea.getText() + "If found please Call us on our hotline 0452245879\n");
                SlipArea.setText(SlipArea.getText() + "***********************************************************\n");

                Print.setEnabled(true);
                Reset.setEnabled(true);

            } else {
                JOptionPane.showMessageDialog(this, "Eror");
            }

            LoadallMember();
        } catch (Exception ex) {
            Logger.getLogger(MemberPortal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_SubmitJbtnActionPerformed

    private void RefreshJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshJbtnActionPerformed

        clear();
        loadOrdeID();

        Reset.setEnabled(false);
        Print.setEnabled(false);
        SlipArea.setText("");

    }//GEN-LAST:event_RefreshJbtnActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        SlipArea.setText("");
    }//GEN-LAST:event_ResetActionPerformed

    private void ModifyJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyJbtnActionPerformed
        try {
            String mi = JTFMemberID.getText();
            String mn = JTFMemberName.getText();
            String bday = ((JTextField) Birthdate.getDateEditor().getUiComponent()).getText();
            String age = ComboAge.getSelectedItem().toString();
            String email = JTFEmail.getText();
            int tele = Integer.parseInt(JTFTelephone.getText());
            String mp = JTFMembership.getText();

            Member member = new Member(mi, mn, bday, age, email, tele, mp);
            boolean addmember = MemberM_Controller.update(member);
            if (addmember) {
                //JOptionPane.showMessageDialog(this, "Done");
                 int opt = JOptionPane.showConfirmDialog(null, "Do you want to print Membership Card with Modify details?", "Uodate", JOptionPane.YES_NO_OPTION);
                  if(opt==0){SlipArea.setText("**********************************************************\n");
                SlipArea.setText(SlipArea.getText() + "*                          Membership Card                                  *\n");
                SlipArea.setText(SlipArea.getText() + "**********************************************************\n");
                Date obj = new Date();
                String date = obj.toString();
                SlipArea.setText(SlipArea.getText() + "\n" + date + "\n\n");
                SlipArea.setText(SlipArea.getText() + "Member ID                    :" + JTFMemberID.getText() + "\n\n");
                SlipArea.setText(SlipArea.getText() + "Member Name             :" + JTFMemberName.getText() + "\n\n");
                SlipArea.setText(SlipArea.getText() + "Date Of Birth                 :" + ((JTextField) Birthdate.getDateEditor().getUiComponent()).getText() + "\n\n");
                SlipArea.setText(SlipArea.getText() + "Email                             :" + JTFEmail.getText() + "\n\n");
                SlipArea.setText(SlipArea.getText() + "Mobile Number            :" + JTFTelephone.getText() + "\n\n");
                SlipArea.setText(SlipArea.getText() + "Membership Payment :" + JTFMembership.getText() + "\n\n");
                SlipArea.setText(SlipArea.getText() + "***********************************************************\n");
                SlipArea.setText(SlipArea.getText() + "This Card is the Property of PageOne public Library.\n");
                SlipArea.setText(SlipArea.getText() + "If found please Call us on our hotline 0452245879\n");
                SlipArea.setText(SlipArea.getText() + "***********************************************************\n");

                Print.setEnabled(true);
                Reset.setEnabled(true);}

                
            } else {
                JOptionPane.showMessageDialog(this, "Eror");
            }
            LoadallMember();

        } catch (Exception ex) {
            Logger.getLogger(MemberPortal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_ModifyJbtnActionPerformed

    private void Member_tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Member_tblMouseClicked
        int selectedRow = Member_tbl.getSelectedRow();

        String ID = dtm.getValueAt(selectedRow, 0).toString();
        String Name = dtm.getValueAt(selectedRow, 1).toString();
        String birthdate = dtm.getValueAt(selectedRow, 2).toString();
        String age = dtm.getValueAt(selectedRow, 3).toString();
        String email = dtm.getValueAt(selectedRow, 4).toString();
        String tele = dtm.getValueAt(selectedRow, 5).toString();
        String mem = dtm.getValueAt(selectedRow, 6).toString();

        JTFMemberID.setText(ID);
        JTFMemberName.setText(Name);
        ((JTextField) Birthdate.getDateEditor().getUiComponent()).setText(birthdate);
        ComboAge.setSelectedItem(age);
        JTFEmail.setText(email);
        JTFTelephone.setText(tele);
        JTFMembership.setText(mem);
    }//GEN-LAST:event_Member_tblMouseClicked

    private void JTFMemberIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFMemberIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFMemberIDActionPerformed

    private void DeleteJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteJbtnActionPerformed
        try {

            String delete = JTFMemberID.getText();
            boolean deleteMember = MemberM_Controller.deleteMember(delete);
            int opt = JOptionPane.showConfirmDialog(null, "Are You Sure?", "Delete", JOptionPane.YES_NO_OPTION);
            if (opt == 0 && deleteMember) {
                JOptionPane.showMessageDialog(this, "Deleted Successfully");
            } else {
                JOptionPane.showMessageDialog(this, "Delete Unsuccess");
            }
            LoadallMember();
            clear();
        } catch (Exception ex) {
            Logger.getLogger(MemberPortal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_DeleteJbtnActionPerformed

    private void JTFMembershipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFMembershipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFMembershipActionPerformed

    private void JTFMemberNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFMemberNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFMemberNameActionPerformed

    private void JTFEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFEmailActionPerformed

    private void SubmitJbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitJbtn1ActionPerformed
        setVisible(false);
        DashBoard db = new DashBoard();
        db.setVisible(true);
    }//GEN-LAST:event_SubmitJbtn1ActionPerformed

    private void JTFTelephoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFTelephoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFTelephoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MemberPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MemberPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MemberPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MemberPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MemberPortal().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(MemberPortal.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(MemberPortal.class.getName()).log(Level.SEVERE, null, ex);
                } catch (Exception ex) {
                    Logger.getLogger(MemberPortal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Birthdate;
    private javax.swing.JComboBox<String> ComboAge;
    private javax.swing.JButton DeleteJbtn;
    private javax.swing.JPanel FullPanel;
    private javax.swing.JTextField JTFEmail;
    private javax.swing.JTextField JTFMemberID;
    private javax.swing.JTextField JTFMemberName;
    private javax.swing.JTextField JTFMembership;
    private javax.swing.JTextField JTFTelephone;
    private javax.swing.JLabel LibrararyName;
    private javax.swing.JLabel LogoImage;
    private javax.swing.JTable Member_tbl;
    private javax.swing.JButton ModifyJbtn;
    private javax.swing.JPanel NavigationBarPanel;
    private javax.swing.JButton Print;
    private javax.swing.JButton RefreshJbtn;
    private javax.swing.JButton Reset;
    private javax.swing.JTextArea SlipArea;
    private javax.swing.JButton SubmitJbtn;
    private javax.swing.JButton SubmitJbtn1;
    private javax.swing.JLabel TimeAndDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    public void clear() {

        JTFMemberID.setText("");
        JTFMemberName.setText("");
        ComboAge.setSelectedIndex(0);
        Birthdate.setDate(null);
        JTFEmail.setText("");
        JTFTelephone.setText("");
        JTFMembership.setText("");

    }

    private void LoadallMember() throws Exception {

        ArrayList<Member> allMembers = MemberM_Controller.getAllCustomers();
        dtm.setRowCount(0);
        for (Member c : allMembers) {
            Object[] rowData = {c.getMemberID(), c.getMemberName(), c.getBirthdate(), c.getAge(), c.getEmail(), c.getTelephone(), c.getMembership()};
            dtm.addRow(rowData);
        }

    }

    private void loadOrdeID() {
        int i = new Random().nextInt(90000);
        JTFMemberID.setText("ID" + i);
    }

}
